### ISSUE TITLE
Make it work when muted

### ISSUE THREAD

**Issue by BumiMandiasDev** [occ-ai/obs-localvocal#113]
Could you make it judge based on the volume slider rather the mute button? Or perhaps, add a setting that makes it so the mute of the source isn't affected by the mute? (This is to support people who don't use their voice and rather text.

**Comment by royshil** [comment]
there is in fact such a settings
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/4f300eb9-c379-421d-b97e-c8a424f2b23c)
