### ISSUE TITLE
obs-localvocal-0.3.1-windows-x64-cpu 版本安装完无法在麦克风滤镜中找到

### ISSUE THREAD

**Issue by tayiie** [occ-ai/obs-localvocal#121]
![屏幕截图 2024-06-28 100618](https://github.com/occ-ai/obs-localvocal/assets/42790207/7247ee8b-46c8-4e93-b7cb-c5e7e9fa9d47)
![屏幕截图 2024-06-28 100526](https://github.com/occ-ai/obs-localvocal/assets/42790207/28635d15-d228-493e-9cd3-57a2b7dd9303)
![屏幕截图 2024-06-28 100500](https://github.com/occ-ai/obs-localvocal/assets/42790207/04ca1c63-f180-4fa3-8b77-bb5390f7c5b3)
![屏幕截图 2024-06-28 100813](https://github.com/occ-ai/obs-localvocal/assets/42790207/7d82add6-2f43-466e-93b8-6547ae1facd5)
![屏幕截图 2024-06-28 100753](https://github.com/occ-ai/obs-localvocal/assets/42790207/0d2242a9-b22c-4409-9766-4e716e295bb7)
使用exe安装后与压缩包解压两种方式在obs的麦克风滤镜添加处均未找到该插件选项，在安装方法与问题页面也为找到可供参考的解决办法。

**Comment by royshil** [comment]
@tayiie  感谢您的问题 
请提供您的OBS日志，以便我找到问题

**Comment by tayiie** [comment]
感谢，这是两份当天安装时候的obs日志，希望能有线索。
[2024-06-28 10-02-07.txt](https://github.com/user-attachments/files/16046644/2024-06-28.10-02-07.txt)
[2024-06-28 09-56-26.txt](https://github.com/user-attachments/files/16046641/2024-06-28.09-56-26.txt)

**Comment by royshil** [comment]
@tayiie 
`10:02:09.012: OBS 29.1.3 (64-bit, windows)`
不支持。 仅支持v30+。

**Comment by tayiie** [comment]
感谢，在手动更新后，安装问题已经解决。
