### ISSUE TITLE
I want to save vocal detection to a file AND shows it on OBS at the same time

### ISSUE THREAD

**Issue by noripico** [occ-ai/obs-localvocal#123]
I want to save vocal detection to a file AND shows it on OBS at the same time. Subtitle doesn't appear once I choose to save it a file. I know adding two Local Vocal plugins to the mic can realize it, but it would be better if you could have that option available.

**Comment by royshil** [comment]
@noripico have you tried adding a text source and getting it to read from the file that LV is saving?
granted your file might be an SRT.. then this won't work well

**Comment by noripico** [comment]
thx for the update. But how can I apply it? I found you have made 4 new files, but I don't know where they should go in my PC.

**Comment by royshil** [comment]
@noripico in here https://github.com/occ-ai/obs-localvocal/actions/runs/9819328473#artifacts you will find downloads (scroll down) so just install the version you need

**Comment by noripico** [comment]
Thx. First of all, I updated LV from 0.3.1 to 0.3.2 and I found a bug. Even though I try to change the language from "Auto detect" to Japanese, which is my mother tongue, it goes back to Auto detect.

**Comment by royshil** [comment]
@noripico let's take that up in a separate issue
but for the multiple outputs - does that work for you?

**Comment by royshil** [comment]
this is now working
