### ISSUE TITLE
.SRT timestamp when renaming file issue

### ISSUE THREAD

**Issue by TheTawnyFool** [occ-ai/obs-localvocal#132]
Hi, I have .srt output enabled, and renaming the file to the clip name. I believe this should create a .srt tile with timestamps that start at 00:00:00

1
21:57:26,674 --> 21:57:29,326
Alright, welcome back guys, Tawny Fool

2
21:57:29,326 --> 21:57:32,738
blah blah

3
21:57:33,408 --> 21:57:36,216
words and more important words

4
21:57:36,216 --> 21:57:37,265
ending words

I don't believe the files are usable, as the timestamps need to match up with the beginning of the clips.  Do I have something set up wrong, or is there a solution?

Thank you so much.

**Comment by TheTawnyFool** [comment]
I am on windows, and have a nvidia GPU.  I am in the CST timezone, and the examples above were around 4 something pm.

**Comment by royshil** [comment]
i've tested this to work properly
but also made some light changes in #134 
so should be fixed in the coming version

**Comment by royshil** [comment]
@TheTawnyFool can you confirm or reject a fix in v0.3.3?

**Comment by TheTawnyFool** [comment]
A quick test and install looks pretty good to me.  I'll let you know after some use if I see any issues.

Thanks!!!

**Comment by royshil** [comment]
done.
