### ISSUE TITLE
Need help understanding difference between "cuda" vs "cudaclblast"

### ISSUE THREAD

**Issue by sarim** [occ-ai/obs-localvocal#133]
What is the difference? for example: obs-localvocal-0.3.2-windows-x64-cuda11.8.0.zip
cuda download files are large, cudaclblast is small.

**Comment by royshil** [comment]
clblast is using OpenCL acceleration so that AMD based systems can enjoy acceleration
the "cudaclblast" is a mistake, it should just be "clblast"
cuda files are bg because they also bring the CUDA DLLs needed for working

**Comment by royshil** [comment]
stale, closing
