### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by L3gion132** [occ-ai/obs-localvocal#45]
Subtitles show [Skip] when not generating as well as the time for the subtitles remaining on screen is to short for people to read them

**Comment by L3gion132** [comment]
![1](https://github.com/obs-ai/obs-localvocal/assets/81138945/1cf0e6ff-5c73-415e-9748-b58a4f4ce693)
![2](https://github.com/obs-ai/obs-localvocal/assets/81138945/a2292c88-9a54-4c1b-bbe5-0ac8c5631e52)
![3](https://github.com/obs-ai/obs-localvocal/assets/81138945/d18b2612-2419-48b6-b4d9-002522ad10cb)

**Comment by royshil** [comment]
I can make some changes to address this
Like a minimum display time for captions as well as not showing "skip"

**Comment by royshil** [comment]
implemented in #46 

@L3gion132 can you please test the build artifacts? 🙏

**Comment by L3gion132** [comment]
> implemented in #46
> 
> @L3gion132 can you please test the build artifacts? 🙏

Hi How do I go about doing that?

**Comment by royshil** [comment]
@L3gion132 every pull request builds artifacts
https://github.com/obs-ai/obs-localvocal/actions/runs/6681222435#artifacts

download the ones you need, you'll find the plugin inside the .zip

**Comment by L3gion132** [comment]
Thanks Testing currently and it works wonders no issues with the time on screen and the [Skip] is gone thank you for the fantastic work

**Comment by royshil** [comment]
resolved
