### ISSUE TITLE
Still character issue?

### ISSUE THREAD

**Issue by makotoihara** [occ-ai/obs-localvocal#48]
When I tested LocalVolcal v0.05 (binary from this github) with OBS 29.1.3 on Windows10, Japanese can not be transcribed properly as bellow.

![obs-issue](https://github.com/occ-ai/obs-localvocal/assets/121211561/992c852d-3592-40ae-8a4d-7995a567caba)
"Text file output" was also same.

Setting with some other languages, such as Chinese and Korean, gave the same kind of characters.
I confirmed that already mentioned languages at #41 are properly processed in my environment.

**Comment by royshil** [comment]
Ok I will have a look at japanese and other languages.
It's very strange there's no one solution to fit all languages.
This is fixable.

**Comment by royshil** [comment]
i've finally found the definitive fix
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/d5990acb-cd6e-4919-860d-2f2d53263fcc)
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/af11b9c7-9d95-4240-a583-99f4e935f3d5)
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/1a5911b0-7358-4def-91f3-b19335c6be57)
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/7e734fb4-515d-4938-a58d-75d4ac362fdb)
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/8d468086-9e8a-44ec-bee9-856250ba5e64)
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/18f124e3-cfa8-4699-afa3-07aeced6041a)
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/fad064cb-93a8-4a3b-a396-aa2b5753594d)
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/a34f2de2-7f6b-45aa-9633-c382b47de5c7)

**Comment by royshil** [comment]
@makotoihara i fixed the issue
Korean characters work for me (see above)
can you test https://github.com/occ-ai/obs-localvocal/actions/runs/6745930037?pr=47#artifacts ?
install the new plugin build on top of the old one

**Comment by makotoihara** [comment]
@royshil Updated version worked fine!! 
Thank you very much for taking time.

**Comment by royshil** [comment]
#47 resolved
