### ISSUE TITLE
Unable to find after installation

### ISSUE THREAD

**Issue by OaimIsGnay** [occ-ai/obs-localvocal#52]
<img width="308" alt="image" src="https://github.com/occ-ai/obs-localvocal/assets/58240619/c0802397-520c-4168-b240-91051330e024">

**Comment by royshil** [comment]
@OaimIsGnay LocalVocal appears as an audio filter, not a source. Look for it under filters for the audio source you want to caption

**Comment by OaimIsGnay** [comment]
> @OaimIsGnay LocalVocal appears as an audio filter, not a source. Look for it under filters for the audio source you want to caption

Thank you. I found it later
