### ISSUE TITLE
RPM package version for Fedora/RHEL

### ISSUE THREAD

**Issue by andersonid** [occ-ai/obs-localvocal#53]
Thank you so much for all your effort and sharing your awesome work, royshilkrot!
Could you please add a RPM package version to install localvocal on Fedora/RHEL?

Thanks!

**Comment by royshil** [comment]
@andersonid i wonder if instructions on how to build and install on Fedora would suffice
like https://github.com/occ-ai/obs-backgroundremoval/blob/main/docs/BUILDING-FEDORA.md

github unfortunately don't provide a Fedora runner
and i'm not sure RPMs created on Ubuntu would work...

**Comment by andersonid** [comment]
> @andersonid i wonder if instructions on how to build and install on Fedora would suffice like https://github.com/occ-ai/obs-backgroundremoval/blob/main/docs/BUILDING-FEDORA.md
> 
> github unfortunately don't provide a Fedora runner and i'm not sure RPMs created on Ubuntu would work...

Thanks, mate.  I will try it out and give you a feedback.

**Comment by andersonid** [comment]
Hi @royshil  I had followed you doc recommendation, but got this error trying to compile while running build-linux script.

```
[9/19] Performing install step for 'Whispercpp_Build'
-- Installing: /home/anobre/Downloads/obs-plugins/obs-localvocal/build_x86_64/Whispercpp_Build-prefix/lib/static/libwhisper.a
-- Installing: /home/anobre/Downloads/obs-plugins/obs-localvocal/build_x86_64/Whispercpp_Build-prefix/include/whisper.h
[19/19] Linking CXX shared module obs-localvocal.so
FAILED: obs-localvocal.so 
: && /usr/bin/c++ -fPIC -O2 -g -DNDEBUG   -shared  -o obs-localvocal.so CMakeFiles/obs-localvocal.dir/obs-localvocal_autogen/mocs_compilation.cpp.o CMakeFiles/obs-localvocal.dir/src/plugin-main.c.o CMakeFiles/obs-localvocal.dir/src/transcription-filter.cpp.o CMakeFiles/obs-localvocal.dir/src/transcription-filter.c.o CMakeFiles/obs-localvocal.dir/src/whisper-processing.cpp.o CMakeFiles/obs-localvocal.dir/src/model-utils/model-downloader.cpp.o CMakeFiles/obs-localvocal.dir/src/model-utils/model-downloader-ui.cpp.o  /usr/lib64/libobs-frontend-api.so.29  _deps/libcurl_fetch-src/lib/libcurl.a  libplugin-support.a  /usr/lib64/libobs.so.29  /usr/lib64/libQt6Widgets.so.6.5.2  /usr/lib64/libQt6Gui.so.6.5.2  /usr/lib64/libGLX.so  /usr/lib64/libOpenGL.so  /usr/lib64/libQt6Core.so.6.5.2  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  /usr/lib64/libz.so  Whispercpp_Build-prefix/lib/static/libwhisper.a && :
/usr/bin/ld: libplugin-support.a(plugin-support.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by royshil** [comment]
@andersonid the error suggests that `libplugin-support.a` wasn't built with `-fPIC`
i've merged a change to add -fPIC on linux
can you git pull master and try the build again?

**Comment by royshil** [comment]
@andersonid are you getting any luck building for fedora?

**Comment by andersonid** [comment]
> @andersonid are you getting any luck building for fedora?

Thank you so much, mate!
It's now installed and visually working on my filters dialog for audio inputs... Now I will try to get the entire solution working with your youtube tutorial.   

Thank you again for sharing this awesome work!!!!
