### ISSUE TITLE
Building latest version with CUDA fails

### ISSUE THREAD

**Issue by Destroy666x** [occ-ai/obs-localvocal#57]
These errors are shown for what worked before and what's in documentation:
![image](https://github.com/occ-ai/obs-localvocal/assets/3606072/30473af4-9f57-4989-aa90-bcc40e6c591a)

Did the command change or something? If so, would be great to update documentation (also, the part about moving DLLs is not needed anymore).

**Comment by royshil** [comment]
i need to look into the CUDA build... thanks for bringing it up!

probably can remove the DLLs copy (they should be found by the operating system)

**Comment by royshil** [comment]
@Destroy666x can you check out #58 plz?

**Comment by Destroy666x** [comment]
Confirming that it works again. CPU usage also seems to have gone down further now

**Comment by royshil** [comment]
yes. improvements from whisper.cpp ...

closing
