### ISSUE TITLE
Subtitles not Showing on Screen 

### ISSUE THREAD

**Issue by PhoebeCheng9911** [occ-ai/obs-localvocal#61]
Hi, 
I am using a Mac M1 with OBS 30.0.0. I want to have the subtitles shown on my screen. I watched your Youtube Video but I cannot find the option subtitle in the dropdown of the Subtitle Outputs (it only have None and Text File Output). Thank you for your help! 
<img width="611" alt="image" src="https://github.com/occ-ai/obs-localvocal/assets/90079020/725d09a9-4422-42be-8af3-1ef4e53026b2">

**Comment by royshil** [comment]
Create a new Text Source on your scene
Then in the drop-down you will see it as an output option.
It just lists all the text sources, and I had one called e.g. "subtitles"

**Comment by PhoebeCheng9911** [comment]
Thank you for the help!
