### ISSUE TITLE
Text Log

### ISSUE THREAD

**Issue by 90sCraig** [occ-ai/obs-localvocal#63]
Is there a way to store the transcriptions to a text file as a log?

I know you can do this with subtitle format, but I would like to be able to say "save the last x lines to a text file".

Or even the ability to say, log the last x minutes of dialog.

**Comment by royshil** [comment]
i got another person asking the same
i can implmenent this as an additional checkbox to not truncate the txt file output
![image](https://github.com/occ-ai/obs-localvocal/assets/441170/c3ebd588-3d05-4c51-a9ad-5094cc40337a)
