### ISSUE TITLE
OBS is crashing when attempting to create LocalVocal filter on MacBook Pro M1

### ISSUE THREAD

**Issue by chadwpry** [occ-ai/obs-localvocal#67]
This is my first time useing the Local Vocal plugin and have not yet seen it work correctly. I'll describe my process and a crash report in hopes that may help provide clarity.

Steps to create issue:

1. Found release of obs-localvocal on github releases page. Used [version 0.1.0 macos-universal.pkg](https://github.com/occ-ai/obs-localvocal/releases/download/0.1.0/obs-localvocal-0.1.0-macos-universal.pkg)
2. Installed package with default installer settings
3. Open OBS
4. Create new scene for testing
5. Create new Audio Input Capture within new scene with MacBook Pro Microphone as the device (not system default) -- attempted to use default device as well later as a test, no difference
6. Select Audio Input from Sources
7. Open filters -- note: no audio filter are setup
8. Add LocalVocal Transcription
9. Provide default name for filter
10. Click ok to the dialog
11. OBS crashes

[local-vocal-crash-report.txt](https://github.com/occ-ai/obs-localvocal/files/14231485/local-vocal-crash-report.txt)

**Comment by chadwpry** [comment]
Just a note. I would have added the crash report inline, but the size was larger than allowable.

**Comment by royshil** [comment]
Seems to fail when trying to load the model and init ggml.. strange. 
I'm unable to try it on my hardware because I have an old Intel Mac.
Try to see the model files exist in the right location.
Although I doubt it is the reason it fails.
Again - hard for me to verify and debug.
You can reach out on Discord and let's see if anyone else with Apple Silicone Mac is running into problems.

**Comment by chadwpry** [comment]
Appreciate the response Roy!

Not sure if the plugin is the right tool for my usecase, so I may just hold off on continuing to troubleshoot. It seems like a push to talk mechanism, with a hotkey or streamdeck button, may work better at the operating system or another application level. I did however look into openai/whisper, whisper.cpp, and go-emotion for sentiment analysis. All of which are local installations which was perfect. Thank you for the pointer to openai/whisper and whisper.ccp in your README. Think I may just go down the route of attempting to control the microphone external of OBS at this point and interopt to the other tools

Feel free to close this issue, unless you want to keep it open for others who may run across the same situation.

Cheers!

**Comment by CR0CKER** [comment]
I can confirm this. Crashes every time I'm trying clicking OK after the filter name dialogue. No workarounds so far.

**Comment by royshil** [comment]
@CR0CKER can you provide logs please? from Intel and M1

**Comment by CR0CKER** [comment]
Thanks for the quick response, @royshil! Here are the logs. The Intel Mac seems to crash after briefly showing the config options, while the M1 crashes immediately after clicking OK in the filter naming dialogue. 

Sounds like an amazing plugin, so I hope we can get it to work. 

[2024-03-20 13-53-29.txt](https://github.com/occ-ai/obs-localvocal/files/14662181/2024-03-20.13-53-29.txt)
[2024-03-20 13-30-24.txt](https://github.com/occ-ai/obs-localvocal/files/14662182/2024-03-20.13-30-24.txt)

**Comment by royshil** [comment]
@CR0CKER the Intel logs doesn't show LV trying to open the model, while the M1 does and apparently crashes on the model load part - which aligns with @chadwpry above
i'm hesitant to conclude that LV causes the crash on Intel during model loading since it doesn't log anything.
i've tested the plugin to work on Intel Mac machines.
can you verify the crash by removing the plugin and adding it again?

for the M1 it's hard for me to catch the bug since i don't have the machine to dev and test, i'll have to rely on you all for testing, e.g. from a PR with potential fix

**Comment by CR0CKER** [comment]
Thanks, @royshil -- I'll try getting it to work on the intel machine first. For the M1 fix, I'm happy to test any beta versions you have, but I'm not a developer so I can't help with coding.

**Comment by royshil** [comment]
@CR0CKER can you plz try the artifacts from #76 e.g. https://github.com/occ-ai/obs-localvocal/actions/runs/8354294570?pr=76
download the macos version from there and install
lmk if it help in any way

**Comment by CR0CKER** [comment]
Thanks -- still crashing, unfortunately. I also tried reinstalling on the Intel Mac and it keps crashing. Other filters install fine, so I'm pretty certain the Intel crash is also caused by LocalVocal.

**Comment by royshil** [comment]
im now going to build separately for M1 and x86
this will not only bring performance boost but also resolve the crash on arm64 for unsupported instructions.

**Comment by royshil** [comment]
@chadwpry @CR0CKER are you able to try the M1 artifcats on https://github.com/occ-ai/obs-localvocal/actions/runs/8359597687 ?

**Comment by CR0CKER** [comment]
Thanks, @royshil -- I've tried it but after replacing the default installation file with the artifact you linked to (arm64), the plugin doesn't appear as an option in the filter dialogue in OBS. Odd.

**Comment by royshil** [comment]
@CR0CKER Thanks for trying it
Can you upload your obs log please?

**Comment by CR0CKER** [comment]
Here you go, @royshil !
[2024-03-21 09-34-24.txt](https://github.com/occ-ai/obs-localvocal/files/14720603/2024-03-21.09-34-24.txt)

**Comment by royshil** [comment]
@CR0CKER this is very strange
Your arm computer is looking for x86_64 binaries
This leads me to believe OBS is running on Rosetta 2 and emulating x86_64 rathe than native arm64

Will you be able to test the x86_64 version for Mac?

**Comment by CR0CKER** [comment]
@royshil you're right! I've reinstalled the Apple silicon version from the OBS website and it's working now with the artefacts you shared! Great.

**Comment by royshil** [comment]
@CR0CKER I've released now an official version so you can use that instead of the artifact

Thanks for verifying
