### ISSUE TITLE
external whisper models won't load at all

### ISSUE THREAD

**Issue by alfarme** [occ-ai/obs-localvocal#68]
Hi,

thank you for this amazing plugin! I am about to use it for a live stream of a swiss german speaker this weekend (hoping you read this and can reply in time:), and I can't get other whisper models to work with  the plugin.

here is an excerpt of the errors: 

> 21:30:01.398: [obs-localvocal] Loading whisper model from C:/Users/xxx/AppData/Roaming/obs-studio/plugin_config/obs-localvocal/models/pytorch_model.bin
> 21:30:04.420: [obs-localvocal] Failed to load whisper model
> 21:30:04.511: [obs-localvocal] whisper_model_path_external modified
> 21:30:04.511: [obs-localvocal] External model file is already loaded
> 21:30:04.511: [obs-localvocal] starting whisper thread
> 21:30:04.511: [obs-localvocal] Whisper context is null, exiting thread
> 21:30:04.511: [obs-localvocal] exiting whisper thread
> 21:30:04.519: [obs-localvocal] External model file is already loaded
> 21:30:04.519: [obs-localvocal] External model file is already loaded
> 21:34:51.630: [obs-localvocal] Loading whisper model from C:/Users/xxx/Downloads/whister_large_v2.bin
> 21:34:58.500: [obs-localvocal] Failed to load whisper model
> 21:34:58.801: [obs-localvocal] whisper_model_path_external modified
> 21:34:58.801: [obs-localvocal] External model file is already loaded
> 21:34:58.802: [obs-localvocal] starting whisper thread
> 21:34:58.802: [obs-localvocal] Whisper context is null, exiting thread
> 21:34:58.802: [obs-localvocal] exiting whisper thread
> 21:34:58.845: [obs-localvocal] External model file is already loaded
> 21:34:58.846: [obs-localvocal] External model file is already loaded
> 21:35:03.118: [obs-localvocal] transcription_filter_properties
> 21:35:03.118: [obs-localvocal] whisper_model_path_external modified
> 21:35:03.118: [obs-localvocal] External model file is already loaded
> 21:35:24.869: [obs-localvocal] Loading whisper model from C:/Users/xxx/Downloads/whister_large_v3.bin
> 21:35:27.960: [obs-localvocal] Failed to load whisper model
> 21:35:28.056: [obs-localvocal] whisper_model_path_external modified
> 21:35:28.056: [obs-localvocal] External model file is already loaded
> 21:35:28.056: [obs-localvocal] starting whisper thread
> 21:35:28.056: [obs-localvocal] Whisper context is null, exiting thread
> 21:35:28.056: [obs-localvocal] exiting whisper thread
> 21:35:28.067: [obs-localvocal] External model file is already loaded
> 21:35:28.068: [obs-localvocal] External model file is already loaded
> 21:36:49.423: [obs-localvocal] Loading whisper model from C:/Users/xxx/Downloads/whister_small.bin
> 21:36:50.600: [obs-localvocal] Failed to load whisper model
> 21:36:50.632: [obs-localvocal] whisper_model_path_external modified
> 21:36:50.632: [obs-localvocal] External model file is already loaded
> 21:36:50.632: [obs-localvocal] starting whisper thread
> 21:36:50.633: [obs-localvocal] Whisper context is null, exiting thread

thank you!

**Comment by royshil** [comment]
Hi - do you have any special characters in the model file path?
On windows the special characters in the path may result in error loading the file

**Comment by royshil** [comment]
stale
