### ISSUE TITLE
OBS crashes after installing the plugin on Ubuntu22.04 based Pop Os system

### ISSUE THREAD

**Issue by vpgits** [occ-ai/obs-localvocal#84]
- OBS was installed by adding the OBS's PPA repository and then installing through the APT repository's latest release. `OBS Studio - 30.1.2` .
- The plugin was compiled using instructions in the readme file.
- Upon compiling, the compiled files were copied over to the respective  /usr sub-directories.
- After the files were copied, OBS would initially crash, then upon launching again, prompts to start the application in safe mode where all plugins are disabled.
- Opening obs through the terminal revealed some information related to the bug.
- `~$ obs
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/themes
debug: Attempted path: /usr/share/obs/obs-studio/themes
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
warning: [Safe Mode] Unclean shutdown detected!
warning: [Safe Mode] User elected to launch normally.
info: Using EGL/X11
info: CPU Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
info: CPU Speed: 1075.724MHz
info: Physical Cores: 8, Logical Cores: 16
info: Physical Memory: 15570MB Total, 2890MB Free
info: Kernel Version: Linux 6.8.0-76060800daily20240311-generic
info: Distribution: "Pop!_OS" "22.04"
info: Desktop Environment: pop:GNOME (pop)
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
info: Qt Version: 6.2.4 (runtime), 6.2.4 (compiled)
info: Portable mode: false
info: OBS 30.1.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 550.67, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
info: NV12 texture support enabled
info: P010 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
info: [pipewire] Available captures:
info: [pipewire]     - Desktop capture
info: [pipewire]     - Window capture
warning: v4l2loopback not installed, virtual camera disabled
info: [obs-browser]: Version 2.23.4
info: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2594+g17f8588+chromium-103.0.5060.134 (compiled)
info: NVENC supported
info: VAAPI: API version 1.14
info: FFmpeg VAAPI H264 encoding supported
info: FFmpeg VAAPI AV1 encoding not supported
info: FFmpeg VAAPI HEVC encoding supported
obs: symbol lookup error: /usr//lib/x86_64-linux-gnu/obs-plugins/obs-localvocal.so: undefined symbol: GetX86Info
obs: symbol lookup error: /usr//lib/x86_64-linux-gnu/obs-plugins/obs-localvocal.so: undefined symbol: GetX86Info`

**Comment by sogaiu** [comment]
I experienced a similar result, i.e. getting `undefined symbol: GetX86Info` during launch of obs.

I tried compiling using the instructions in the README and I also tried the `.deb` files for 0.2.3 and 0.2.4 from the releases page.  In all three cases I got the same sort of result mentioned above about `undefined symbol`.

Grepping through the locally cloned repository after building, I  noticed use of what looked like [CTranslate2](https://github.com/OpenNMT/CTranslate2).

That seems to use `GetX86Info` in at least one place, [here](https://github.com/OpenNMT/CTranslate2/blob/9d54f5d7f5a9c03d54f105601f7b625461e72d41/src/cpu/cpu_info.cc#L12):

```
namespace ctranslate2 {
  namespace cpu {

    static const cpu_features::X86Info info = cpu_features::GetX86Info();
```

May be this is related to the issue?

**Comment by royshil** [comment]
@sogaiu @vpgits i believe i resolved the issue in #94 by bundling cpu_features 
can you test?

**Comment by sogaiu** [comment]
@royshil I had success via the branch mentioned in https://github.com/occ-ai/obs-localvocal/pull/94.  By "success" I mean that OBS does not crash for me now and I am able to see evidence of LocalVocal in OBS' UI.

My environment was Xubuntu 22.04.4 in a VM.

The following are a few things I did that were slightly different from the instructions:

1. The CI script seems to have a different name now, so adapted the name (left off the trailing `.sh`).
2. Manually did `sudo apt install libssl-dev` without which the script would not complete.
3. Set the environment variables `OBS_PLUGINS_PATH` and `OBS_PLUGINS_DATA_PATH` to `$(repo)/release/RelWithDebInfo/lib/x86_64-linux-gnu/obs-plugins` and `$(repo)/release/RelWithDebInfo/share/obs/obs-plugins` respectively (where `$(repo)` is the full path to the locally cloned repository).

---

On a side note, I had difficulty in figuring out how to put the resulting files and directories under `~/.config/obs-studio/plugins` -- I'm still not quite sure (^^;  Perhaps this is not the place to mention it, as it is not specific to this plugin, but FWIW.

In any case, thanks for this plugin and the fix.

**Comment by royshil** [comment]
@sogaiu ok i'm going to merge in #94 as a fix and ive also updated the build instructions for linux. thank you!

**Comment by sogaiu** [comment]
This part of the updated instructions:

```
$ export OBS_PLUGINS_PATH=$(pwd)/release/RelWithDebInfo/lib/x86_64-linux-gnu/obs-plugins
$ export OBS_PLUGINS_DATA_PATH=$(pwd)/release/RelWithDebInfo/share/obs/obs-plugins
```

seems slightly out of place.

As I understand it, those environment variables are what OBS uses to find plugin bits when it starts up / is running.  I don't think they are used during the build (though I may be wrong about that).

What I have yet to figure out is how to arrange the resulting built files and directories to live under `~/.config/obs-studio/plugins`.  Once that is determined, IIUC, the environment variables shouldn't need to be set.

Unfortunately, I haven't had much luck finding good info about how yet.  I suppose one could repeatedly try different arrangements in combination with examining the output of `strace`...may be there's some other plugin that documents this that I haven't found yet (^^;

**Comment by sogaiu** [comment]
I found a hint [here](https://wiki.archlinux.org/title/Open_Broadcaster_Software#Manual_plugins_installation).

May be adapting the following will work:

```
~/.config/obs-studio/plugins/plugin_name/bin/64-bit/plugin_name.so
~/.config/obs-studio/plugins/plugin_name/data/locale/en-US.ini
```

**Comment by sogaiu** [comment]
The instructions from the Arch Wiki were ever so slightly off.

Changing `64-bit` to `64bit` in one of the paths yielded success here.

The file / directory layout that worked here was:

```
~/.config/obs-studio/plugins$ tree
.
└── obs-localvocal
    ├── bin
    │   └── 64bit
    │       ├── obs-localvocal
    │       │   ├── libonnxruntime_providers_shared.so
    │       │   └── libonnxruntime.so.1.17.1
    │       └── obs-localvocal.so
    └── data
        ├── locale
        │   ├── ar-SA.ini
        │   ├── de-DE.ini
        │   ├── en-US.ini
        │   ├── es-ES.ini
        │   ├── fr-FR.ini
        │   ├── hi-IN.ini
        │   ├── ja-JP.ini
        │   ├── ko-KR.ini
        │   ├── pl-PL.ini
        │   ├── pt-BR.ini
        │   ├── ru-RU.ini
        │   └── zh-CN.ini
        └── models
            ├── ggml-model-whisper-tiny-en
            │   └── ggml-model-whisper-tiny.en.bin
            └── silero-vad
                └── silero_vad.onnx
```

**Comment by royshil** [comment]
@sogaiu so as an instruction to folks does this make sense?
```sh
$ mkdir -p ~/.config/obs-studio/plugins/obs-localvocal
$ sudo cp -R release/RelWithDebInfo/lib/* ~/.config/obs-studio/plugins/obs-localvocal
$ sudo cp -R release/RelWithDebInfo/share/* ~/.config/obs-studio/plugins/obs-localvocal
```

**Comment by sogaiu** [comment]
@royshil I think I tried something like before that but did not find it to work.

Adjusting the source and destination paths a bit, I found the following to work here:

```
$ mkdir -p ~/.config/obs-studio/plugins/obs-localvocal/bin/64bit
$ cp -R release/RelWithDebInfo/lib/x86_64-linux-gnu/obs-plugins/* ~/.config/obs-studio/plugins/obs-localvocal/bin/64bit/
$ mkdir -p ~/.config/obs-studio/plugins/obs-localvocal/data
$ cp -R release/RelWithDebInfo/share/obs/obs-plugins/obs-localvocal/* ~/.config/obs-studio/plugins/obs-localvocal/data/
```

---

On a side note, I did not use `sudo` because the destination is within a user's home directory and is likely to be writable.

**Comment by ogmkp** [comment]
Updated to 0.2.4 and same error: undefined symbol: GetX86Info

**Comment by sogaiu** [comment]
> Updated to 0.2.4 and same error: undefined symbol: GetX86Info

IIUC, 0.2.4 predates the changes that royshil made to address the reported error about "undefined symbol", so I think it won't be enough to modify the paths involved in copying.

ATM, I think it's necessary to build from source (and follow the updated instructions) as described [here](https://github.com/occ-ai/obs-localvocal?tab=readme-ov-file#linux-ubuntu).

**Comment by royshil** [comment]
the latest version shuold take care of this @ogmkp @sogaiu @vpgits can you all test plz?

**Comment by sogaiu** [comment]
I tried via the `.deb` for 0.2.6 as well as compiling from source (and copying things under `~/.config/obs-studio/plugins` in the latter case).

Installation went ok and looking out the output in the console, the plugin appeared to be detected.

I tried adding an audio capture device (alsa) source and then a corresponding filter for LocalVocal.  The addition appeared successful in the GUI, but shortly after obs crashed.

Below is the console output from one of the sessions.

<details>
<pre>
$ obs
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/themes
debug: Attempted path: /usr/share/obs/obs-studio/themes
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
info: CPU Speed: 1497.600MHz
info: CPU Name: 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
info: CPU Speed: 1497.600MHz
info: Physical Cores: 2, Logical Cores: 2
info: Physical Memory: 3911MB Total, 1740MB Free
info: Kernel Version: Linux 5.15.0-107-generic
info: Distribution: "Ubuntu" "22.04"
info: Desktop Environment: XFCE (xubuntu)
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
info: Qt Version: 6.2.4 (runtime), 6.2.4 (compiled)
info: Portable mode: false
info: OBS 30.1.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
libEGL warning: DRI2: failed to authenticate
info: Loading up OpenGL on adapter Mesa llvmpipe (LLVM 15.0.7, 256 bits)
info: OpenGL loaded successfully, version 4.5 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2, shading language 4.50
info: ---------------------------------
info: video settings reset:
	base resolution:   1024x768
	output resolution: 640x480
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
info: NV12 texture support enabled
info: P010 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
info: [pipewire] No captures available
info: [obs-browser]: Version 2.23.4
info: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2594+g17f8588+chromium-103.0.5060.134 (compiled)
info: FFmpeg VAAPI H264 encoding not supported
info: FFmpeg VAAPI AV1 encoding not supported
info: FFmpeg VAAPI HEVC encoding not supported
info: [obs-localvocal] plugin loaded successfully (version 0.2.6)
info: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.4.2 | RPC Version: 1)
info: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.2.4 | Qt version (run-time): 6.2.4
info: [obs-websocket] [obs_module_load] Linked ASIO Version: 101801
info: [obs-websocket] [obs_module_load] Module loaded.
info: [vlc-video]: VLC 3.0.16 Vetinari found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-qsv11.so
info:     obs-outputs.so
info:     obs-localvocal.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-pipewire.so
info:     linux-jack.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-output-ui.so
info:     decklink-captions.so
info: ---------------------------------
warning: QWidget::setTabOrder: 'first' and 'second' must be in the same window
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 15.99.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor' (default)
info: [Loaded global audio device]: 'Desktop Audio'
info: pulse-input: Server name: 'pulseaudio 15.99.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.pci-0000_00_1b.0.analog-stereo' (default)
info: [Loaded global audio device]: 'Mic/Aux'
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info: ------------------------------------------------
info: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Desktop Audio)

info: alsa-input: PCM 'default' rate set to 44100
info: alsa-input: PCM 'default' channels set to 2
info: User added source 'Audio Capture Device (ALSA)' (alsa_input_capture) to scene 'Scene'
info: [obs-localvocal] filter defaults
info: [obs-localvocal] LocalVocal filter create
info: [obs-localvocal] create text source
info: User added source 'LocalVocal Subtitles' (text_ft2_source_v2) to scene 'Scene'
info: [obs-localvocal] Checking if model 'Whisper Tiny En' exists in data...
info: [obs-localvocal] TokenBufferThread::monitor
info: [obs-localvocal] Model folder found in data: /usr/share/obs/obs-plugins/obs-localvocal/models/ggml-model-whisper-tiny-en
info: [obs-localvocal] TokenBufferThread::monitor: done
info: [obs-localvocal] Model bin file found in folder: /usr/share/obs/obs-plugins/obs-localvocal/models/ggml-model-whisper-tiny-en/ggml-model-whisper-tiny.en.bin
2024-05-14 12:01:09.173363571 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '131'. It is not used by any node and should be removed from the model.
2024-05-14 12:01:09.173422569 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '136'. It is not used by any node and should be removed from the model.
2024-05-14 12:01:09.173430144 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '139'. It is not used by any node and should be removed from the model.
2024-05-14 12:01:09.173436950 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '140'. It is not used by any node and should be removed from the model.
2024-05-14 12:01:09.173444158 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '134'. It is not used by any node and should be removed from the model.
2024-05-14 12:01:09.173499911 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '628'. It is not used by any node and should be removed from the model.
2024-05-14 12:01:09.173505228 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '623'. It is not used by any node and should be removed from the model.
2024-05-14 12:01:09.173509805 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '629'. It is not used by any node and should be removed from the model.
2024-05-14 12:01:09.173514871 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '620'. It is not used by any node and should be removed from the model.
2024-05-14 12:01:09.173523974 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '625'. It is not used by any node and should be removed from the model.
info: [obs-localvocal] Loading whisper model from /usr/share/obs/obs-plugins/obs-localvocal/models/ggml-model-whisper-tiny-en/ggml-model-whisper-tiny.en.bin
info: [obs-localvocal] Using CPU for inference
info: [obs-localvocal] DTW token timestamps disabled
info: [obs-localvocal] Whisper model loaded: AVX = 1 | AVX2 = 0 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0
info: User added filter 'LocalVocal Transcription' (transcription_filter_audio_filter) to source 'Audio Capture Device (ALSA)'
info: [obs-localvocal] starting whisper thread
info: [obs-localvocal] filter defaults
info: [obs-localvocal] whisper_model_path_external modified
Segmentation fault (core dumped)
</pre>
</details>

**Comment by royshil** [comment]
@ogmkp can you try v0.3.0 with the fix?

**Comment by sogaiu** [comment]
FWIW, with [052de4f4](https://github.com/occ-ai/obs-localvocal/commit/052de4f47437bf1c43bc1eb78ec7baa310353249) I no longer experience the crash :)

**Comment by royshil** [comment]
i think we can close this for now and open a new ticket when more evidence arrives
