### ISSUE TITLE
OBS crash while downloading Whisper Model

### ISSUE THREAD

**Issue by PowerfulDot** [occ-ai/obs-localvocal#86]
I'm experiencing a silent crash (no crash log produced by OBS) when trying to change Whisper Model. On plugin version version 0.2.1. During the download, it just closes out. I am on Windows 10 and have reproduced this on two PCs. Am happy to provide more info needed to help.

**Comment by royshil** [comment]
@PowerfulDot thanks for the feedback - can you please try the artifacts from #85 ? i've resolved a number of bugs re the crashes

**Comment by PowerfulDot** [comment]
Apologies it took me awhile to get back to this. How do I try the artifacts from that?

**Comment by royshil** [comment]
@PowerfulDot  new version https://github.com/occ-ai/obs-localvocal/releases/tag/0.2.2 should fix this

**Comment by PowerfulDot** [comment]
Lovely, thanks much!

**Comment by PowerfulDot** [comment]
Works flawlessly! And I am so excited to have the new CUDA option. My poor CPU couldn't handle the transcription on its own, and used a two PC setup for a bit. You are the bestest.
