### ISSUE TITLE
Adding its own lines of CC.

### ISSUE THREAD

**Issue by ShawnDriscoll** [occ-ai/obs-localvocal#91]
It keeps displaying "Thank you." and "We'll see you back in a minute." Or variations of. On occasion. When I end a sentence while talking.

**Comment by royshil** [comment]
Yeah that's a known "bug" of the speech recognition model. The best way to get rid of such things is to add a noise cancellation filter before (above) the localvocal filter.
However I am also trying to get rid of it on the plugin level.

**Comment by ShawnDriscoll** [comment]
Ok.

**Comment by royshil** [comment]
@ShawnDriscoll are you able to test the latest artifacts from #92 ?
